### PR TITLE
remove event listener + optional background color

### PR DESCRIPTION
**Pull request by scstan**
- remove click event listener after selection
- add optional different background color
- prevent buttons and links click through

### CODE REVIEW

**Comment by scstan** [comment]
@jamesbechet 
Hi!
Please take a look at this pull request.

**Comment by jamesbechet** [comment]
@scstan thanks for the pull request. Could you fix the tests before I can take a look at it?

**Comment by scstan** [comment]
@jamesbechet tests are working now.
It still clicks through "New pull request" button, any idea why that is happening and how we can prevent it ?
http://snpy.in/qyG9dF

**Comment by jamesbechet** [comment]
@scstan thanks, it will be merged soon.
I'm not sure why this is happening though.

**Pull request merged**
